#!/bin/sh
CONF=/etc/config/qpkg.conf
QPKG_NAME=qdk

case "$1" in
  start)
    ENABLED=$(/sbin/getcfg $QPKG_NAME Enable -u -d FALSE -f $CONF)
    if [ "$ENABLED" != "TRUE" ]; then
        echo "$QPKG_NAME is disabled."
        exit 1
    fi
    QDK_DIR=$(/sbin/getcfg $QPKG_NAME Install_Path -d "" -f $CONF)
    [ -x $QDK_DIR/bin/qbuild ] && /bin/ln -sf $QDK_DIR/bin/qbuild /usr/bin/qbuild
    ;;

  stop)
    /bin/rm -f /usr/bin/qbuild
    ;;

  restart)
    $0 stop
    $0 start
    ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0
