#!/bin/sh
#prerm remove
#old-prerm upgrade new-version
#new-prerm failed-upgrade old-version

set -e
source /etc/profile
QPKG_NAME=@@PACKAGE@@
CONF=/etc/config/qpkg.conf
QPKG_DIR=${QPKG_DIR:-$(/sbin/getcfg $QPKG_NAME Install_Path -d "" -f $CONF)}

case "$1" in
  remove)
    capp destroy ${QPKG_DIR}/container.json
    ;;
  upgrade)
    ;;
  failed-upgrade)
    ;;
  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
