#!/bin/sh
#postrm remove
#postrm purge
#old-postrm upgrade new-version
#new-postrm failed-upgrade old-version
#new-postrm abort-install
#new-postrm abort-install old-version
#new-postrm abort-upgrade old-version

set -e
APP_BASE=${PWD}

case "$1" in
  remove)
    ;;
  purge)
    ;;
  upgrade)
    ;;
  failed-upgrade)
    ;;
  abort-install)
    ;;
  abort-upgrade)
    ;;
  *)
    echo "prerm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

exit 0
